### ISSUE TITLE
dumpprivkey in windows 10 doesn't seem to work

### ISSUE THREAD

**Issue by urban-idler** [Crowndev/crowncoin#31]
tried different syntaxes and in both a windows 10 wallet as well as a wallet on a VM, the dumpprivkey doesn't work in the debug console window.

**Comment by urban-idler** [comment]
Stonehedge stated that the dumpprivkey works when you do it in two commands:
~$ Walletpassphrase [passphrase] [time to leave unlocked]
~$ dumpprivkey [CRW Address]

The help in the wallet debug console states:

dumpprivkey "crowncoinaddress"

Reveals the private key corresponding to 'crowncoinaddress'.
Then the importprivkey can be used with this output

Arguments:
1. "crowncoinaddress" (string, required) The Crowncoin address for the private key

Result:
"key" (string) The private key

Examples:
> crowncoin-cli dumpprivkey "myaddress"
> crowncoin-cli importprivkey "mykey"
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "dumpprivkey", "params": ["myaddress"] }' -H 'content-type: text/plain;' http://127.0.0.1:9341/
(code -1)

I for some reason thought that you could tack the walletpassphrase onto the end of the command similar to the way other commands like the throne start commands function.  

This should probably be made consistent one way or another.

**Comment by Infernoman** [comment]
Alright with the next release this should be made consistent just going to do some testing to make sure i've gotten everything in order, the throne start commands should no longer accept a password along with the commands which will also hopefully solve a deadlocking issue with start-many and start-disabled.
you will be required to unlock then start. same as dumping your private key or sending coins.

**Comment by Infernoman** [comment]
closing this issue for now, if there is still an issue with the new release coming up please re-open the issue.
