### ISSUE TITLE
dumpprivkey <6fdc546d-62a6-49ef-95a3-abdc8f8e1fb0>

### ISSUE THREAD

**Issue by Nazar199328** [Crowndev/crowncoin#44]
dumpprivkey <1PhRyhGwNToV3F7pVQ8Wmjy44brTPmrcD5>

**Comment by Nazar199328** [comment]
bitcoin.conf

**Comment by Infernoman** [comment]
Sorry I'm not quite sure what the issue is? Could you please explain your issue a bit more.
