### ISSUE TITLE
Chinese translation of the coin name in qt

### ISSUE THREAD

**Issue by zhanzhenzhen** [Crowndev/crowncoin#78]
Now the coin name is translated to "达世币", which actually means "Dash Coin" ("达" pronounces "da", "世" pronounces "shi", and "币" means (not pronounces) coin). I found that in Dash, every translation doesn't translate the coin name, except for Chinese. The same goes for Bitcoin.

I suggest translating into "Crown币"，or simply "Crown", or "王冠币" or "皇冠币". Note that "冠" itself means crown, but Chinese like to use double-character words so it looks better to add a "王" (means king) or "皇" (means emperor) before it.

**Comment by ashotkhachatryan** [comment]
So we can replace "达世币" with "王冠币"?
For example 'Send coins to a Crown address' translated as '发送币至达世币地址' now it should be
发送币至王冠币地址 ?

**Comment by zhanzhenzhen** [comment]
Yes, but I think "皇冠" looks better than "王冠" because 皇冠 used more often in China. Google these 2 words:

王冠: 30,800,000 results
皇冠: 96,700,000 results

But if you want it to be consistent among all languages, just use Crown is also good.

**Comment by zhanzhenzhen** [comment]
Also, don't forget "達世幣" (in traditional Chinese zh-tw file) which should also be replaced with "王冠幣", "皇冠幣", or just "Crown".

**Comment by ashotkhachatryan** [comment]
So '发送币至达世币地址' -> '发送币至Crown地址'?

**Comment by zhanzhenzhen** [comment]
yeah, that looks good.
